services:
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=tickets;Username=postgres;Password=postgres;
    ports:
      - "80:80"
  
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tickets
    ports:
      - "5433:5432"
    restart: always