name: CI
on:
  pull_request:
    branches: [ "LabWork5" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Start containers
        run: docker-compose -f "./Lab-Work-5/code/api-lab/docker-compose.yml" up  -d